# Generated by Django 5.1 on 2024-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseValidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
